const options = [
  { value: "animals", label: "Animals"},
  { value: "art", label: "Art"},
  { value: "community", label: "Community"},
  { value: "cultural awareness", label: "Cultural Awareness"},
  { value: "curiosity", label: "Curiosity"},
  { value: "decision making", label: "Decision Making"},
  { value: "emotional skills", label: "Emotional Skills"},
  { value: "empathy", label: "Empathy"},
  { value: "history", label: "History"},
  { value: "imaginative play", label: "Imaginative Play"},
  { value: "making observations", label: "Making Observations"},
  { value: "making predictions", label: "Making Predicitons"},
  { value: "nature", label: "Nature"},
  { value: "literacy", label: "Literacy"},
  { value: "persistence", label: "Persistence"},
  { value: "problem solving", label: "Problem Solving"},
  { value: "science", label: "Science"},
  { value: "social skills", label: "Social Skills"},
  { value: "outerspace", label: "Outerspace"},
  { value: "teamwork", label: "Teamwork"},
  { value: "vocabulary", label: "Vocabulary"},
]

export default options