const showTitles = [
  "Alma's Way",
  'Arthur',
  'The Cat in the Hat',
  'Clifford the Big Red Dog',
  'Curious George',
  'Cyberchase',
  "Daniel Tiger's Neighborhood",
  'Dinosaur Train',
  'Donkey Hodie',
  'Elinor Wonders Why',
  'Hero Elementary',
  "Let's Go Luna",
  'Martha Speaks',
  'Molly of Denali',
  'Nature Cat',
  'Odd Squad',
  'Peg + Cat',
  'Pinkalicious',
  'Ready Jet Go!',
  'Sesame Street',
  'Sid the Science Kid',
  'Splash and Bubbles',
  'Super Why',
  'Wild Kratts',
  'Word Girl',
  'Xavier Riddle and the Secret Museum'
]

export default showTitles